"""Generate all paper figures (PNG, 300 dpi) from results/*.csv."""
import os, sys
import numpy as np, pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from sklearn.decomposition import PCA
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

os.makedirs('figs', exist_ok=True)
plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 9, 'axes.spines.top': False,
                     'axes.spines.right': False, 'axes.grid': True, 'grid.color': '#e6e5e0',
                     'grid.linewidth': 0.6, 'axes.edgecolor': '#52514e', 'axes.labelcolor': '#0b0b0b',
                     'xtick.color': '#52514e', 'ytick.color': '#52514e', 'legend.frameon': False})
STYLE = {  # fixed order, entity-bound colours + marker as secondary encoding
    'SEW-GSP':   dict(color='#2a78d6', marker='o', lw=2.0, ls='-'),
    'HIACSP-WF': dict(color='#eb6834', marker='s', lw=1.6, ls='-'),
    'HIACSP':    dict(color='#1baf7a', marker='^', lw=1.6, ls='-'),
    'HIBOG':     dict(color='#eda100', marker='D', lw=1.6, ls='-'),
    'Raw':       dict(color='#8a8986', marker='x', lw=1.4, ls='--'),
}
ORDER = ['Raw', 'HIBOG', 'HIACSP', 'HIACSP-WF', 'SEW-GSP']


def save(fig, name):
    fig.savefig(f'figs/{name}.png', dpi=300, bbox_inches='tight', facecolor='white')
    os.makedirs('figs/submission', exist_ok=True)               # Springer: vector + high-res copies
    fig.savefig(f'figs/submission/{name}.pdf', bbox_inches='tight', facecolor='white')
    fig.savefig(f'figs/submission/{name}.eps', bbox_inches='tight', facecolor='white')
    fig.savefig(f'figs/submission/{name}.tif', dpi=600, bbox_inches='tight', facecolor='white',
                pil_kwargs={'compression': 'tiff_lzw'})
    plt.close(fig)


# ------------------------------------------------------------------ Fig. 1 framework
# Fig. 1 (framework diagram) is drawn by hand; its source is figs/fig1_framework.svg and the
# raster/vector exports are figs/fig1_framework.png and figs/submission/fig1_framework.{pdf,eps,tif}.
# It is therefore not generated by this script.


# ------------------------------------------------------------------ Fig. 2 weight recovery
def fig_weights():
    d = pd.read_csv('results/weights.csv')
    fig, axs = plt.subplots(1, 3, figsize=(7.4, 2.5))
    cols = {'CNLR (proposed)': '#2a78d6', 'Variance (HIACSP-WF)': '#eb6834', 'Laplacian score': '#1baf7a'}
    mk = {'CNLR (proposed)': 'o', 'Variance (HIACSP-WF)': 's', 'Laplacian score': '^'}
    for ax, nt in zip(axs[:2], ['uniform', 'gaussian']):
        g = d[d.noise == nt].groupby(['weighting', 'm'])['mass_inf'].mean().unstack(0)
        for c in cols:
            ax.plot(g.index, g[c], color=cols[c], marker=mk[c], lw=1.8, ms=4, label=c)
        ax.set_xscale('log', base=2); ax.set_xticks([5, 10, 20, 40, 80]); ax.set_xticklabels([5, 10, 20, 40, 80])
        ax.set_ylim(0, 1.02); ax.set_xlabel('number of irrelevant features m')
        ax.set_title(f'({"a" if nt=="uniform" else "b"}) {nt} irrelevant features', fontsize=8.5)
    axs[0].set_ylabel('weight mass on\ninformative features')
    p = pd.read_csv('results/weights_wine_n20.csv')
    x = p.feature.values
    axs[2].bar(x - 0.2, p['Variance (HIACSP-WF)'], 0.4, color='#eb6834', label='Variance (HIACSP-WF)')
    axs[2].bar(x + 0.2, p['CNLR (proposed)'], 0.4, color='#2a78d6', label='CNLR (proposed)')
    axs[2].axvline(12.5, color='#52514e', lw=0.8, ls=':')
    axs[2].set_ylim(0, axs[2].get_ylim()[1] * 1.12)
    axs[2].text(6, axs[2].get_ylim()[1] * 0.93, '13 original', ha='center', fontsize=7)
    axs[2].text(23, axs[2].get_ylim()[1] * 0.93, '20 noise', ha='center', fontsize=7)
    axs[2].set_xlabel('feature index (Wine+N20)'); axs[2].set_ylabel('weight')
    axs[2].set_title('(c) learned weights', fontsize=8.5)
    h, l = axs[0].get_legend_handles_labels()
    fig.legend(h, l, ncol=3, loc='upper center', bbox_to_anchor=(0.5, 1.08), fontsize=7.5)
    fig.tight_layout(); save(fig, 'fig2_weights')


# ------------------------------------------------------------------ Fig. 3 noise robustness
def fig_noise():
    d = pd.read_csv('results/noise.csv')
    g = d.groupby(['data', 'm', 'method'])['ARI'].mean().reset_index()
    fig, axs = plt.subplots(1, 4, figsize=(7.4, 2.3), sharey=False)
    for ax, (dn, title) in zip(axs, [('Synthetic', '(a) Synthetic'), ('iris', '(b) Iris'),
                                     ('wine', '(c) Wine'), ('wdbc', '(d) WDBC')]):
        for m in ORDER:
            s = g[(g.data == dn) & (g.method == m)]
            ax.plot(s.m, s.ARI * 100, ms=3.5, label=m, **STYLE[m])
        ax.set_title(title, fontsize=8.5); ax.set_xlabel('irrelevant features m')
    axs[0].set_ylabel('mean ARI (%)')
    h, l = axs[0].get_legend_handles_labels()
    fig.legend(h, l, ncol=5, loc='upper center', bbox_to_anchor=(0.5, 1.08), fontsize=7.5)
    fig.tight_layout(); save(fig, 'fig3_noise')


# ------------------------------------------------------------------ Fig. 4 scalability
def fig_scal():
    d = pd.read_csv('results/scalability.csv')
    fig, axs = plt.subplots(1, 2, figsize=(6.4, 2.4))
    f = d.dropna(subset=['t_full'])
    axs[0].plot(f.n, f.t_full, color='#eb6834', marker='s', lw=1.8, ms=4, label='all-pairs Dijkstra (HIACSP)')
    axs[0].plot(d.n, d.t_trunc, color='#2a78d6', marker='o', lw=1.8, ms=4, label='truncated Dijkstra (ours)')
    axs[0].set_xscale('log'); axs[0].set_yscale('log'); axs[0].set_xlabel('N'); axs[0].set_ylabel('time of geodesic K-NN (s)')
    axs[0].legend(fontsize=7); axs[0].set_title('(a) runtime', fontsize=8.5)
    axs[1].plot(d.n, d.mem_full_MB, color='#eb6834', marker='s', lw=1.8, ms=4, label='N x N distance matrix')
    axs[1].plot(d.n, d.mem_trunc_MB, color='#2a78d6', marker='o', lw=1.8, ms=4, label='N x K neighbour lists')
    axs[1].set_xscale('log'); axs[1].set_yscale('log'); axs[1].set_xlabel('N'); axs[1].set_ylabel('memory (MB)')
    axs[1].legend(fontsize=7); axs[1].set_title('(b) memory', fontsize=8.5)
    fig.tight_layout(); save(fig, 'fig4_scalability')


# ------------------------------------------------------------------ Fig. 5 sensitivity
def fig_sens():
    from sewsp.evalkit import MAIN_DATASETS
    d = pd.read_csv('results/main_all.csv')
    d = d[d.method.isin(ORDER[1:]) & d.dataset.isin(MAIN_DATASETS)]
    fig, axs = plt.subplots(1, 2, figsize=(6.4, 2.4), sharey=True)
    for m in ORDER[1:]:
        s = d[d.method == m].groupby('K')['ARI'].mean() * 100
        axs[0].plot(s.index, s.values, ms=3.5, label=m, **STYLE[m])
        s = d[d.method == m].groupby('d')['ARI'].mean() * 100
        axs[1].plot(s.index, s.values, ms=3.5, label=m, **STYLE[m])
    axs[0].set_xlabel('number of neighbours K'); axs[1].set_xlabel('iterations d')
    axs[0].set_ylabel('mean ARI (%)'); axs[0].set_title('(a) averaged over d', fontsize=8.5)
    axs[1].set_title('(b) averaged over K', fontsize=8.5); axs[1].legend(fontsize=7)
    fig.tight_layout(); save(fig, 'fig5_sensitivity')


# ------------------------------------------------------------------ Fig. 6 PCA view
def fig_pca():
    from sewsp.core import METHODS
    from sewsp.evalkit import load
    X, y = load('wine+N20')
    cols = ['#2a78d6', '#eb6834', '#1baf7a']
    fig, axs = plt.subplots(1, 4, figsize=(7.4, 2.0))
    for ax, m in zip(axs, ['Raw', 'HIACSP', 'HIACSP-WF', 'SEW-GSP']):
        Z = METHODS[m](X, 10, 5)[-1]
        P = PCA(2).fit_transform(Z)
        for c in range(3):
            ax.scatter(P[y == c + 1, 0], P[y == c + 1, 1], s=6, color=cols[c], lw=0, label=f'class {c+1}')
        ax.set_title(m, fontsize=8.5); ax.set_xticks([]); ax.set_yticks([]); ax.grid(False)
    axs[0].legend(fontsize=6.5, loc='best', markerscale=1.5)
    fig.tight_layout(); save(fig, 'fig6_pca')


if __name__ == '__main__':
    for f in [fig_weights, fig_noise, fig_scal, fig_sens, fig_pca]:
        try:
            f(); print('ok', f.__name__)
        except FileNotFoundError as e:
            print('skip', f.__name__, e)
